@echo off
if exist front-end\.git (
    echo Removing nested git...
    rmdir /s /q front-end\.git
)
echo Initializing git...
git init
echo Adding remote...
git remote add origin https://github.com/KhalidFinny/f1-telemetry-dashboard.git
echo Adding files...
git add .
echo Committing...
git commit -m "Initial commit of full project"
echo Renaming branch...
git branch -M main
echo Done.
